theme = "congo"
baseURL = "https://wasatyogrodnik.github.io/"
defaultContentLanguage = "pl"

[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
